FROM debian:11 AS Base

RUN apt update
RUN apt install -y gcc busybox meson ninja-build unzip zip

FROM Base AS Build

WORKDIR /build

ENTRYPOINT ["/usr/bin/env", "sh", "-c", "busybox sh build_ft.sh"]

