FROM debian:11 AS Base

RUN apt update
RUN apt install -y g++ gcc busybox meson ninja-build unzip zip git

FROM Base AS Build

WORKDIR /build

ENTRYPOINT ["/usr/bin/env", "sh", "-c", "busybox sh build_ft.sh freetype_slim_glibc"]

