FROM alpine:3.19 AS Base

RUN apk update
RUN apk add --no-cache gcc busybox cmake samurai unzip zip patch musl-dev libstdc++-dev g++

FROM Base AS Build

WORKDIR /build

ENTRYPOINT ["/usr/bin/env", "sh", "-c", "busybox sh build_ft.sh freetype_slim_musl"]

